// Templates for webpages
package main

const ReportLastTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>All groups last errors :: HLS Probe II</title>
<meta name="description" content="Creating a table with Twitter Bootstrap. Learn how to use Twitter Bootstrap toolkit to create Tables with examples.">
<link href="/css/bootstrap.css" rel="stylesheet">
</head>
<body><h1>Last errors</h1>
<table class="table table-bordered table-condensed">
        <thead>
          <tr>
            <th>Group</th>
            <th>Name</th>
            <th>Status</th>
            <th>Content Length</th>
            <th>Request Duration</th>
            <th>Last Checked</th>
            <th>Error</th>
          </tr>
        </thead>
        <tbody>
        {{#TableData}}
          <tr class="{{severity}}">
            <td>{{group}}</td>
            <td><a href="{{uri}}">{{name}}</a></td>
            <td>{{status}}</td>
            <td>{{contentlength}}</td>
            <td>{{elapsed}}</td>
            <td>{{started}}</td>
            <td>{{error}}</td>
          </tr>
        {{/TableData}}
        </tbody>
</table>
Generated by <a href="http://github.com/grafov/hlsprobe2">HLS Probe II</a>
</body>
</html>
`

const ReportGroupLastTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{#Vars}}{{group}} :: {{/Vars}}HLS Probe II</title>
<meta name="description" content="Creating a table with Twitter Bootstrap. Learn how to use Twitter Bootstrap toolkit to create Tables with examples.">
<link href="/css/bootstrap.css" rel="stylesheet">
</head>
<body>{{#Vars}}<h1>{{group}} last errors</h1>{{/Vars}}
<table class="table table-bordered table-condensed">
        <thead>
          <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Content Length</th>
            <th>Request Duration</th>
            <th>Last Checked</th>
            <th>Error</th>
          </tr>
        </thead>
        <tbody>
        {{#TableData}}
          <tr class="{{severity}}">
            <td><a href="{{uri}}">{{name}}</a></td>
            <td>{{status}}</td>
            <td>{{contentlength}}</td>
            <td>{{elapsed}}</td>
            <td>{{started}}</td>
            <td>{{error}}</td>
          </tr>
        {{/TableData}}
        </tbody>
</table>
Generated by <a href="http://github.com/grafov/hlsprobe2">HLS Probe II</a>
</body>
</html>
`
